description = "Ubuntu jammy base image with buildpacks for Java, .NET Core, NodeJS, Go, Python, PHP, Ruby, Apache HTTPD, NGINX and Procfile"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/procfile:5.6.0"
  version = "5.6.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/python:2.8.0"
  version = "2.8.0"

[lifecycle]
  version = "0.16.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/python"
    version = "2.8.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.6.0"

# Base images used to create the builder
[build]
image = "mwrightpivotal/cv-stack-build:1.0"
[run]
[[run.images]]
image = "mwrightpivotal/cv-stack-build:1.0"
